/**
 * Created by yotam on 22/12/2016.
 */
angular.module('myApp.room')

    .service('RoomService', ['$rootScope', function ($rootScope) {
        var Rooms = firebase.database().ref('roomies/rooms');
        var _images = [
            {
                "path": "air-conditioner-1.png",
                "scale" : 1.5
            },
            {"path": "armchair.png", "scale" : 1.5
            },
            {"path": "armchair-1.png", "scale" : 1.5},
            {"path": "armchair-2.png","scale" : 1.5},
            {"path": "armchair-3.png", "scale" : 1.5},
            {"path": "armchair-4.png", "scale" : 1.5},
            {"path": "armchair-5.png", "scale" : 1.5},
            {"path": "armchair-6.png", "scale" : 1.5},
            {"path": "armchair-7.png", "scale" : 1.5},
            {"path": "bathtub.png", "scale" : 2},
            {"path": "bathtub-1.png", "scale" : 2},
            {"path": "bathtub-2.png", "scale" : 2},
            {"path": "bed.png","scale" : 2},
            {"path": "bed-1.png", "scale" : 2},
            {"path": "bed-2.png", "scale" : 2},
            {"path": "blender.png"},
            {"path": "boiler.png"},
            {"path": "bonsai.png"},
            {"path": "bookcase.png","scale" : 2},
            {"path": "bookcase-1.png","scale" : 2},
            {"path": "bookshelf.png","scale" : 2},
            {"path": "bookshelf-1.png","scale" : 2},
            {"path": "bookshelf-2.png","scale" : 2},
            {"path": "bookshelf-3.png","scale" : 2},
            {"path": "bookshelf-4.png","scale" : 2},
            {"path": "cactus.png"},
            {"path": "cactus-1.png"},
            {"path": "chair.png", "scale" : 1.3},
            {"path": "chair-1.png", "scale" : 1.3},
            {"path": "chair-2.png", "scale" : 1.3},
            {"path": "chair-3.png", "scale" : 1.3},
            {"path": "chair-4.png", "scale" : 1.3},
            {"path": "chair-5.png", "scale" : 1.3},
            {"path": "chandelier.png"},
            {"path": "chest-of-drawers.png", "scale" : 1.5},
            {"path": "chest-of-drawers-1.png", "scale" : 1.5},
            {"path": "chest-of-drawers-2.png", "scale" : 1.5},
            {"path": "chest-of-drawers-3.png", "scale" : 1.5},
            {"path": "chest-of-drawers-4.png", "scale" : 1.5},
            {"path": "chest-of-drawers-5.png", "scale" : 1.5},
            {"path": "chest-of-drawers-6.png", "scale" : 1.5},
            {"path": "chest-of-drawers-7.png", "scale" : 1.5},
            {"path": "closet.png", "scale" : 2},
            {"path": "closet-1.png", "scale" : 2},
            {"path": "closet-2.png", "scale" : 2},
            {"path": "closet-3.png", "scale" : 2},
            {"path": "closet-4.png", "scale" : 2},
            {"path": "coffee-machine.png"},
            {"path": "cooker.png","scale" : 1.5},
            {"path": "cooler.png"},
            {"path": "couch.png", "scale" : 2},
            {"path": "couch-1.png", "scale" : 2},
            {"path": "couch-2.png", "scale" : 2},
            {"path": "couch-3.png", "scale" : 2},
            {"path": "couch-4.png", "scale" : 2},
            {"path": "couch-5.png", "scale" : 2},
            {"path": "couch-6.png", "scale" : 2},
            {"path": "couch-7.png", "scale" : 2},
            {"path": "couch-8.png", "scale" : 2},
            {"path": "couch-9.png", "scale" : 2},
            {"path": "couch-10.png", "scale" : 2},
            {"path": "couch-11.png", "scale" : 2},
            {"path": "desk.png", "scale" : 1.5},
            {"path": "desk-1.png","scale" : 1.5},
            {"path": "desk-2.png","scale" : 1.5},
            {"path": "desk-3.png","scale" : 1.5},
            {"path": "desk-4.png","scale" : 1.5},
            {"path": "dishwasher.png","scale" : 1.5},
            {"path": "door.png","scale" : 2},
            {"path": "door-1.png","scale" : 2},
            {"path": "door-2.png","scale" : 2},
            {"path": "door-3.png","scale" : 2},
            {"path": "door-4.png","scale" : 2},
            {"path": "door-5.png","scale" : 2},
            {"path": "door-6.png","scale" : 2},
            {"path": "dressing.png","scale" : 2},
            {"path": "dressing-1.png","scale" : 2},
            {"path": "dressing-2.png","scale" : 2},
            {"path": "fireplace.png","scale" : 2},
            {"path": "fireplace-1.png","scale" : 2},
            {"path": "fireplace-2.png","scale" : 2},
            {"path": "fireplace-3.png","scale" : 2},
            {"path": "flower.png"},
            {"path": "flower-1.png"},
            {"path": "food-steamer.png","scale" : 1.5},
            {"path": "fridge.png","scale" : 2},
            {"path": "fridge-1.png","scale" : 2},
            {"path": "fridge-2.png","scale" : 2},
            {"path": "garage.png","scale" : 3},
            {"path": "hanger.png","scale" : 2},
            {"path": "hanger-1.png","scale" : 2},
            {"path": "hanger-2.png","scale" : 2},
            {"path": "heater.png","scale" : 2},
            {"path": "hood.png","scale" : 2},
            {"path": "iron.png"},
            {"path": "juicer.png"},
            {"path": "lamp.png"},
            {"path": "lamp-1.png"},
            {"path": "lamp-2.png"},
            {"path": "lamp-3.png"},
            {"path": "lamp-4.png"},
            {"path": "lamp-5.png"},
            {"path": "lamp-6.png"},
            {"path": "lamp-7.png"},
            {"path": "library.png","scale" : 2.5},
            {"path": "light-bulb.png"},
            {"path": "light-bulb-1.png"},
            {"path": "light-bulb-2.png"},
            {"path": "light-bulb-3.png"},
            {"path": "light-bulb-4.png"},
            {"path": "light-bulb-5.png"},
            {"path": "light-bulb-6.png"},
            {"path": "light-bulb-7.png"},
            {"path": "light-bulb-8.png"},
            {"path": "light-bulb-9.png"},
            {"path": "lights.png"},
            {"path": "living-room.png","scale" : 2},
            {"path": "livingroom.png","scale" : 2},
            {"path": "livingroom-1.png","scale" : 2},
            {"path": "livingroom-2.png","scale" : 2},
            {"path": "meat-grinder.png"},
            {"path": "microwave.png"},
            {"path": "microwave-1.png"},
            {"path": "mixer.png"},
            {"path": "mixer-1.png"},
            {"path": "mixer-2.png"},
            {"path": "mixer-3.png"},
            {"path": "nightstand.png","scale" : 1.5},
            {"path": "nightstand-1.png","scale" : 1.5},
            {"path": "nightstand-2.png","scale" : 1.5},
            {"path": "office-chair.png","scale" : 1.5},
            {"path": "office-chair-1.png","scale" : 1.5},
            {"path": "office-chair-2.png","scale" : 1.5},
            {"path": "office-chair-3.png","scale" : 1.5},
            {"path": "office-chair-4.png","scale" : 1.5},
            {"path": "office-chair-5.png","scale" : 1.5},
            {"path": "office-chair-6.png","scale" : 1.5},
            {"path": "office-chair-7.png","scale" : 1.5},
            {"path": "office-chair-8.png","scale" : 1.5},
            {"path": "office-chair-9.png","scale" : 1.5},
            {"path": "office-chair-10.png","scale" : 1.5},
            {"path": "office-chair-11.png","scale" : 1.5},
            {"path": "ottoman.png","scale" : 1.5},
            {"path": "pipe.png"},
            {"path": "pipe-1.png"},
            {"path": "pipe-2.png"},
            {"path": "pipe-3.png"},
            {"path": "pipe-4.png"},
            {"path": "pipe-5.png"},
            {"path": "pipe-6.png"},
            {"path": "plant.png"},
            {"path": "plant-1.png"},
            {"path": "plant-2.png"},
            {"path": "plant-3.png"},
            {"path": "radiator.png","scale" : 1.5},
            {"path": "radiator-1.png","scale" : 1.5},
            {"path": "radiator-2.png","scale" : 1.5},
            {"path": "radiator-3.png","scale" : 1.5},
            {"path": "radiator-4.png","scale" : 1.5},
            {"path": "sandwich-maker.png"},
            {"path": "sewing-machine.png"},
            {"path": "shower.png","scale" : 3},
            {"path": "shower-1.png","scale" : 3},
            {"path": "shower-2.png","scale" : 3},
            {"path": "sink.png","scale" : 1.5},
            {"path": "sink-1.png","scale" : 1.5},
            {"path": "sofa.png","scale" : 3},
            {"path": "sofa-1.png","scale" : 3},
            {"path": "sofa-2.png","scale" : 3},
            {"path": "sofa-3.png","scale" : 3},
            {"path": "sofa-4.png","scale" : 3},
            {"path": "sofa-5.png","scale" : 3},
            {"path": "sofa-6.png","scale" : 3},
            {"path": "sofa-7.png","scale" : 3},
            {"path": "sofa-8.png","scale" : 3},
            {"path": "sofa-9.png","scale" : 3},
            {"path": "sofa-10.png","scale" : 3},
            {"path": "sofa-11.png","scale" : 3},
            {"path": "sofa-12.png","scale" : 3},
            {"path": "sofa-13.png","scale" : 3},
            {"path": "sofa-14.png","scale" : 3},
            {"path": "sofa-15.png","scale" : 3},
            {"path": "sofa-16.png","scale" : 3},
            {"path": "sofa-17.png","scale" : 3},
            {"path": "sofa-18.png","scale" : 3},
            {"path": "stairs.png","scale" : 4},
            {"path": "stairs-1.png","scale" : 4},
            {"path": "stool.png","scale" : 1.5},
            {"path": "stool-1.png","scale" : 1.5},
            {"path": "stool-2.png","scale" : 1.5},
            {"path": "stove.png","scale" : 2},
            {"path": "stove-1.png","scale" : 2},
            {"path": "table.png","scale" : 2},
            {"path": "table-1.png","scale" : 2},
            {"path": "table-2.png","scale" : 2},
            {"path": "table-3.png","scale" : 2},
            {"path": "table-4.png","scale" : 2},
            {"path": "table-5.png","scale" : 2},
            {"path": "table-6.png","scale" : 2},
            {"path": "table-7.png","scale" : 2},
            {"path": "tap.png"},
            {"path": "television.png","scale" : 2},
            {"path": "television-1.png","scale" : 2},
            {"path": "television-2.png","scale" : 2},
            {"path": "television-3.png","scale" : 2},
            {"path": "television-4.png","scale" : 2},
            {"path": "toilet.png","scale" : 1.5},
            {"path": "tulips.png"},
            {"path": "vacuum-cleaner.png","scale" : 1.5},
            {"path": "valve.png"},
            {"path": "valve-1.png"},
            {"path": "valve-2.png"},
            {"path": "wall.png","scale" : 3},
            {"path": "wardrobe.png","scale" : 3},
            {"path": "wardrobe-1.png","scale" : 3},
            {"path": "wardrobe-2.png","scale" : 3},
            {"path": "washing-machine.png","scale" : 2},
            {"path": "washing-machine-1.png","scale" : 2},
            {"path": "water-heater.png","scale" : 1.5},
            {"path": "window.png","scale" : 2},
            {"path": "window-1.png","scale" : 2},
            {"path": "window-2.png","scale" : 2},
            {"path": "window-3.png","scale" : 2},
            {"path": "window-4.png","scale" : 2},
            {"path": "window-5.png","scale" : 2},
            {"path": "window-6.png","scale" : 2},
            {"path": "window-7.png","scale" : 2},
            {"path": "window-8.png","scale" : 2},
            {"path": "window-9.png","scale" : 2}]

        var Service = {
            getRoom : function(roomId){
                var roomRef = firebase.database().ref('roomies/rooms/' + roomId);
                return roomRef.once('value').then(function(snapshot) {
                    $rootScope.$broadcast('EXISTING_ROOM_LOADED', snapshot.val());
                    return snapshot.val();
                });
            },
            
            setItem : function(roomId, itemKey, data){
                delete data.key;
                var itemRef = firebase.database().ref('roomies/rooms/' + roomId + '/items/' + itemKey);
                return itemRef.set(data);
            },
            
            addItem : function(roomId, data){
                var itemsRef = firebase.database().ref('roomies/rooms/' + roomId + '/items');
                var newItemRef = itemsRef.push();
                return newItemRef.set(data);
            },
            
            getItemsInventory : function(){
                return _images;
            }
        };

        return Service;
    }]);
